name: work
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup
        run: make setup
      - name: test
        run: make test
      - name: lint
        run: make lint
